---
# Determine how many terrain you want to generate

- num_of_terrains: 1


# Choose the type of terrain from the following list.

# random_uniform_terrain = 0
# stepping_stones_terrain = 1
# pyramid_stairs_terrain = 2
# pyramid_sloped_terrain = 3
# discrete_obstacles_terrain = 4 
# wave_terrain = 5 
# stairs_terrain = 6 
# sloped_terrain = 7
# flat_terrain = 8

# Chosse the type of material from the following list:
# grass
# rock
# ...

###Structure###

# - terrain1:

#     type: 2
#     position: [0.0, 0.0, 0.0] 
#     orientation: [0.0, 0.0, 0.0, 1.0]
#     name: "wave_terrain"
    

# - terrain2:

#     type: 2
#     position: [10.0, 0.0, 0.0] 
#     orientation: [0.0, 0.0, 0.0, 1.0]
#     scale: [1.0, 1.0, 1.0]
#     material: "grass"  
#     name: "pyramid_stairs_terrain"
    
# - terrain3:

#    ... 

- terrain1:

    type: 0
    position: [0.0, 0.0, 0.0] 
    orientation: [0.0, 0.0, 0.0, 1.0]
    material: "Soil_Rocky" 
    name: "non_uniform_terrain"
    width: 10.0
    length: 10.0
    scale: [5, 5, 2]


# - terrain2:

#     type: 2
#     position: [-25, 0.0, 0.0] 
#     orientation: [0.0, 0.0, 0.0, 1.0]
#     material: "Soil_Rocky" 
#     name: "pyramid_stairs_terrains"
#     width: 30.0
#     length: 30.0
#     scale: [5, 5, -5]


# - terrain3:
 
#     type: 5
#     position: [-302.5, 0.0, 0.0] 
#     orientation: [0.0, 0.0, 0.0, 1.0]
#     scale: [5, 5, -5]
#     material: "Sand" 
#     name: "wave_terrain"
#     width: 30.0
#     length: 30.0
#     scale: [5, 5, -5]

# #

- controller: "keyboard" # or position

# - trajectory:

#     type: 'straight_line'
